### ISSUE TITLE
2. Tetris Grid

### ISSUE THREAD

**Issue by LucHighwalker** [MakeSchool-Tutorials/web-7-react-redux-tetris-app#1]
In the 'Define Some CSS' section, `.App-header` is found in `/src/App.css` not `/src/index.css`.

**Comment by anselb** [comment]
In addition to this, the tutorial suggests:
- All css should be in `/src/index.css`. Should we move everything in `/src/App.css` to that file?
- The `/src/App.js` file itself never uses `/src/index.css` but rather `/src/App.css`. Should we replace the imported file?

**Comment by LucHighwalker** [comment]
- Personally I really hate putting everything in the `index.css`. `index.css` should be reserved for things that  are set on a global scale. Like modifying the html or body tag, or setting variables in root. I think putting everything inside `index.css`, while it works for implementing styles quickly, it's generally bad practice. And the more these tutorials enforce good practices, the better as it'll help students make good practices second nature. Ideally, each component would have its own css file. 
- `index.css` is referenced by `index.js`, so it will be at the topmost level, and would get overwritten by the css in `App.css`, since it is called after `index.css`.

**Comment by soggybag** [comment]
The tutorial takes the premise that the components are not reusable and will only be used in this project. For this reason, it puts all styles in index.css. These styles are imported into index.js. 

The styles in App.css are left over from the default create-react-project source. 

Agreed, putting all styles in idnex.css would be bad practice working with a team or planning for scalability. On the other hand, having a single location for all styles in a small project can help to understand how the styles function. 

Feel free to put styles where you think is best.

**Comment by ibirnam** [comment]
Fixed @LucHighwalker 's original bug, clarified why we're putting things all in one file, and also added a stretch challenge for organizing the css better in 7d66f7ddeefe1d6f2f58222e95c32142a52b6b97

Thanks for the feedback all!
