### ISSUE TITLE
6. Arranging the Page

### ISSUE THREAD

**Issue by LucHighwalker** [MakeSchool-Tutorials/web-7-react-redux-tetris-app#3]
The side navigation and the table of contents on top do not match.

[Image](https://drive.google.com/file/d/19dYP_APMZOn-2exVzZr8Tg5XnoUKrH4l/view?usp=sharing)

**Comment by ibirnam** [comment]
@LucHighwalker - fixed up the headers to match more closely now in 44791bd4efc2a2bd6a0b8ad4a9c59419e1cfad3d
