### ISSUE TITLE
9. Actions and Reducers — mismatched code block ```

### ISSUE THREAD

**Issue by noltron000** [MakeSchool-Tutorials/web-7-react-redux-tetris-app#4]
Check this section:
### COMBINE REDUCERS
https://github.com/MakeSchool-Tutorials/web-7-react-redux-tetris-app/blame/master/P08-Actions-and-Reducers/content.md#L204

In markdown, it seems this code block is parsed correctly.

However in the tutorial on Make School, it is formatted at regular paragraph text. 

See the final sentance of this image for details

<img width="1295" alt="Screen Shot 2019-04-04 at 12 54 46 PM" src="https://user-images.githubusercontent.com/19766927/55584386-eec01080-56d8-11e9-8fc5-e96440f1aa34.png">

**Comment by ibirnam** [comment]
@noltron000 -  sorry about that! great catch, and really appreciate you writing out the section header, link to chapter, and image! All of this made it super easy to find where the fix was

Fixed in dd6c72b3b4b94989f1d1b401bf27ce6774591001
