### ISSUE TITLE
9. Actions and Reducers

### ISSUE THREAD

**Issue by nsafai** [MakeSchool-Tutorials/web-7-react-redux-tetris-app#6]
A snippet of code is ending earlier than it should. 

Perhaps there's an extra set of backticks ```? 
![image](https://user-images.githubusercontent.com/6496862/55606683-9b78ad00-572e-11e9-81cc-7ca7324f6e6e.png)

**Comment by ibirnam** [comment]
@nsafai - yup, @noltron000  opened this same issue! Fixed in dd6c72b3b4b94989f1d1b401bf27ce6774591001, but appreciate you putting in the image here, super helpful for debugging!
