### ISSUE TITLE
13. Connect Grid Board

### ISSUE THREAD

**Issue by anselb** [MakeSchool-Tutorials/web-7-react-redux-tetris-app#8]
In the "MAPPING THE GRID TO GRIDSQUARES" section (checkout [line 193](https://github.com/MakeSchool-Tutorials/web-7-react-redux-tetris-app/blame/master/P12-Connect-Grid-Board/content.md)), `square` is getting passed in as a prop to the grid square component and are being used as a child element of the grid square. Neither of these appear to be getting used in `grid-square.js`, so I was wondering if `square` still had any purpose here.

**Comment by ibirnam** [comment]
great catch @anselb ! you're right in that it's not used, was some old test code that accidentally slipped through. Fixed now!
