### ISSUE TITLE
P03-Next-Block

### ISSUE THREAD

**Issue by InesJing2409** [MakeSchool-Tutorials/web-7-react-redux-tetris-app#9]
Hi! Actually this is not a issue, just a question..
Under P03-Next-Block, in section "Make the Next Block Component", there is this part:

// Map the block to the grid    
return box.map((rowArray, row) => {
      return rowArray.map((square, col) => {
        return <GridSquare key={`${row}${col}`} color={0} />;
    });
});

Can you explain it in more detail? It's a bit complicated to me. Also, the variable "square" was never used. May I know why?

**Comment by soggybag** [comment]
Happy to!

First, make sure you understand Array.map(). In a nutshell you call map on an array. The map method takes a function callback as a param. The callback function takes three Params an item from the source array, the index of that item, and the source array. 

The map method returns a new array. Use map to transform an array of one type into an array of another type.  

Here the first map takes an array of arrays and returns an array of arrays.

The second map takes each array of colors, I think these are integers if I recall, and maps them to arrays a GridSquares. Each GridSquare has a couple properties key and color. 

Square probably gets used as the value for color in the next step? I’m on the bus at the moment and don’t have the full source code.

**Comment by InesJing2409** [comment]
I see, that makes it clearer. Thank you so much for the prompt reply! 👍

**Comment by soggybag** [comment]
You’re welcome. Are you a Make School student?

In short this snippet takes the array of colors and transforms these into an array of component views that are displayed.

**Comment by InesJing2409** [comment]
No, I was actually directed to your tutorial from an article. Looks cool so decided to try it. Fingers crossed I can make it work..

**Comment by InesJing2409** [comment]
Hi! I hope it's okay to post all the questions I have here.. :)
Under P04-Score-Board, in section "Create the ScoreBoard Component", refer below, why do you have to state "padding" twice in the css?

/* Score Board */
.score-board-button {
  padding: 0;
  display: block;
  padding: 1em;
  border-width: 5px;
  border-top-color: var(--button-color-t);
  border-left-color: var(--button-color-l);
  border-right-color: var(--button-color-r);
  border-bottom-color: var(--button-color-b);
}

**Comment by soggybag** [comment]
Yes, that's redundant. The second declaration is the one that is used.

**Comment by soggybag** [comment]
This tutorial is used on our web site. You can follow the tutorial there. Some of the markdown is specific to our tutorial system and so doesn't display the same on GitHub. 

https://www.makeschool.com/academy/track/react-redux-tetris-app-tutorial-o4s
